-- Script para popular a tabela users com 100 usuários distintos
-- O ID será gerado automaticamente pela sequência do banco de dados.

INSERT INTO users (name) VALUES ('Ana Beatriz Costa');
INSERT INTO users (name) VALUES ('Bruno Dias de Castro');
INSERT INTO users (name) VALUES ('Carla Martins Faria');
INSERT INTO users (name) VALUES ('Daniel Gomes Lima');
INSERT INTO users (name) VALUES ('Eduarda Nunes de Oliveira');
INSERT INTO users (name) VALUES ('Felipe Pereira Ramos');
INSERT INTO users (name) VALUES ('Gabriela Ribeiro Santos');
INSERT INTO users (name) VALUES ('Heitor Rocha Silva');
INSERT INTO users (name) VALUES ('Isabela Souza Teixeira');
INSERT INTO users (name) VALUES ('João Vítor Torres Alves');
INSERT INTO users (name) VALUES ('Karen Vasconcelos Barros');
INSERT INTO users (name) VALUES ('Lucas Xavier Cardoso');
INSERT INTO users (name) VALUES ('Mariana Yamazaki Dias');
INSERT INTO users (name) VALUES ('Nicolas Zabel Esteves');
INSERT INTO users (name) VALUES ('Olívia Ferreira Gomes');
INSERT INTO users (name) VALUES ('Pedro Henrique de Jesus');
INSERT INTO users (name) VALUES ('Quintino Lopes de Mendonça');
INSERT INTO users (name) VALUES ('Rafaela Nunes de Oliveira');
INSERT INTO users (name) VALUES ('Samuel Pinto de Queiroz');
INSERT INTO users (name) VALUES ('Tatiana Ribeiro da Silva');
INSERT INTO users (name) VALUES ('Ulisses Santos Teixeira');
INSERT INTO users (name) VALUES ('Valentina Vasconcelos de Azevedo');
INSERT INTO users (name) VALUES ('Wagner Xavier de Barros');
INSERT INTO users (name) VALUES ('Xuxa Cardoso da Costa');
INSERT INTO users (name) VALUES ('Yasmin Dias de Faria');
INSERT INTO users (name) VALUES ('Ziraldo Esteves Gomes');
INSERT INTO users (name) VALUES ('Arthur Ferreira de Jesus');
INSERT INTO users (name) VALUES ('Beatriz Lima de Mendonça');
INSERT INTO users (name) VALUES ('Caio Martins de Oliveira');
INSERT INTO users (name) VALUES ('Davi Nunes de Queiroz');
INSERT INTO users (name) VALUES ('Eloá Pereira da Silva');
INSERT INTO users (name) VALUES ('Fernanda Ramos Teixeira');
INSERT INTO users (name) VALUES ('Gustavo Ribeiro de Azevedo');
INSERT INTO users (name) VALUES ('Helena Rocha de Barros');
INSERT INTO users (name) VALUES ('Igor Santos da Costa');
INSERT INTO users (name) VALUES ('Júlia Souza de Faria');
INSERT INTO users (name) VALUES ('Kauan Torres Gomes');
INSERT INTO users (name) VALUES ('Laura Vasconcelos de Jesus');
INSERT INTO users (name) VALUES ('Miguel Xavier de Mendonça');
INSERT INTO users (name) VALUES ('Natália Yamazaki de Oliveira');
INSERT INTO users (name) VALUES ('Otávio Zabel de Queiroz');
INSERT INTO users (name) VALUES ('Pietra Alves da Silva');
INSERT INTO users (name) VALUES ('Quezia Barros Teixeira');
INSERT INTO users (name) VALUES ('Ryan Cardoso de Azevedo');
INSERT INTO users (name) VALUES ('Sofia Dias de Barros');
INSERT INTO users (name) VALUES ('Theo Esteves da Costa');
INSERT INTO users (name) VALUES ('Úrsula Ferreira de Faria');
INSERT INTO users (name) VALUES ('Vinícius Gomes de Jesus');
INSERT INTO users (name) VALUES ('Wanessa Lima de Mendonça');
INSERT INTO users (name) VALUES ('Yago Martins de Oliveira');
INSERT INTO users (name) VALUES ('Zoe Nunes de Queiroz');
INSERT INTO users (name) VALUES ('Alice Pereira da Silva');
INSERT INTO users (name) VALUES ('Breno Ramos Teixeira');
INSERT INTO users (name) VALUES ('Cecília Ribeiro de Azevedo');
INSERT INTO users (name) VALUES ('Diogo Rocha de Barros');
INSERT INTO users (name) VALUES ('Esther Santos da Costa');
INSERT INTO users (name) VALUES ('Fábio Souza de Faria');
INSERT INTO users (name) VALUES ('Giovanna Torres Gomes');
INSERT INTO users (name) VALUES ('Heitor Vasconcelos de Jesus');
INSERT INTO users (name) VALUES ('Isis Xavier de Mendonça');
INSERT INTO users (name) VALUES ('Joaquim Yamazaki de Oliveira');
INSERT INTO users (name) VALUES ('Kaique Zabel de Queiroz');
INSERT INTO users (name) VALUES ('Lara Alves da Silva');
INSERT INTO users (name) VALUES ('Matheus Barros Teixeira');
INSERT INTO users (name) VALUES ('Nicole Cardoso de Azevedo');
INSERT INTO users (name) VALUES ('Oscar Dias de Barros');
INSERT INTO users (name) VALUES ('Pâmela Esteves da Costa');
INSERT INTO users (name) VALUES ('Raul Ferreira de Faria');
INSERT INTO users (name) VALUES ('Sarah Gomes de Jesus');
INSERT INTO users (name) VALUES ('Thiago Lima de Mendonça');
INSERT INTO users (name) VALUES ('Vicente Martins de Oliveira');
INSERT INTO users (name) VALUES ('Yasmin Nunes de Queiroz');
INSERT INTO users (name) VALUES ('Augusto Pereira da Silva');
INSERT INTO users (name) VALUES ('Brenda Ramos Teixeira');
INSERT INTO users (name) VALUES ('Calebe Ribeiro de Azevedo');
INSERT INTO users (name) VALUES ('Daniela Rocha de Barros');
INSERT INTO users (name) VALUES ('Erick Santos da Costa');
INSERT INTO users (name) VALUES ('Flávia Souza de Faria');
INSERT INTO users (name) VALUES ('Guilherme Torres Gomes');
INSERT INTO users (name) VALUES ('Heloísa Vasconcelos de Jesus');
INSERT INTO users (name) VALUES ('Isaac Xavier de Mendonça');
INSERT INTO users (name) VALUES ('Jennifer Yamazaki de Oliveira');
INSERT INTO users (name) VALUES ('Kevin Zabel de Queiroz');
INSERT INTO users (name) VALUES ('Letícia Alves da Silva');
INSERT INTO users (name) VALUES ('Marcos Barros Teixeira');
INSERT INTO users (name) VALUES ('Naomi Cardoso de Azevedo');
INSERT INTO users (name) VALUES ('Otto Dias de Barros');
INSERT INTO users (name) VALUES ('Paula Esteves da Costa');
INSERT INTO users (name) VALUES ('Ricardo Ferreira de Faria');
INSERT INTO users (name) VALUES ('Sabrina Gomes de Jesus');
INSERT INTO users (name) VALUES ('Tiago Lima de Mendonça');
INSERT INTO users (name) VALUES ('Vitória Martins de Oliveira');
INSERT INTO users (name) VALUES ('William Nunes de Queiroz');
INSERT INTO users (name) VALUES ('Alexia Pereira da Silva');
INSERT INTO users (name) VALUES ('Benício Ramos Teixeira');
INSERT INTO users (name) VALUES ('Clarice Ribeiro de Azevedo');
INSERT INTO users (name) VALUES ('Diego Rocha de Barros');